### PR TITLE
Ignore EINVAL from sync()

### PR DESCRIPTION
**Pull request by ammario**

### CODE REVIEW

**Comment by ammario** [comment]
@nhooyr feel free to review this later.

**Comment by nhooyr** [comment]
Can you add this to the syncwriter package instead? @ammario 
There's an existing check there for os.Stderr and os.Stdout.

**Comment by nhooyr** [comment]
https://github.com/cdr/slog/blob/3dcbf1ca5f30c5bfe8c9671cbad92769fda02312/internal/syncwriter/syncwriter.go#L42

**Comment by ammario** [comment]
See #44

**Pull request merged**
